import { useState, useEffect } from 'react'

export default function ReferralStats({ userId }) {
  const [stats, setStats] = useState({
    totalReferrals: 0,
    totalEarned: 0,
    couponsGenerated: 0,
    activeCoupons: 0,
    recentReferrals: []
  })

  useEffect(() => {
    loadReferralStats()
  }, [userId])

  const loadReferralStats = () => {
    // Get all coupons
    const coupons = JSON.parse(localStorage.getItem('referralCoupons') || '[]')
    
    // Get coupons generated by this user
    const myCoupons = coupons.filter(c => c.generatedBy === userId)
    
    // Get used coupons (successful referrals)
    const usedCoupons = myCoupons.filter(c => c.used === true)
    
    // Get recent referrals (last 5)
    const recentReferrals = usedCoupons
      .sort((a, b) => b.usedAt - a.usedAt)
      .slice(0, 5)
      .map(c => ({
        mobile: c.usedBy,
        date: new Date(c.usedAt).toLocaleDateString(),
        amount: 20
      }))
    
    // Get all users for name lookup
    const users = JSON.parse(localStorage.getItem('users') || '[]')
    
    // Add names to recent referrals
    const recentWithNames = recentReferrals.map(ref => {
      const user = users.find(u => u.mobile === ref.mobile)
      return {
        ...ref,
        name: user?.name || 'Unknown'
      }
    })
    
    setStats({
      totalReferrals: usedCoupons.length,
      totalEarned: usedCoupons.length * 20,
      couponsGenerated: myCoupons.length,
      activeCoupons: myCoupons.filter(c => !c.used).length,
      recentReferrals: recentWithNames
    })
  }

  return (
    <div className="bg-gray-800 rounded-xl p-4 mt-4">
      <h3 className="text-white font-semibold text-lg mb-3 flex items-center gap-2">
        🎁 Referral Program
      </h3>
      
      {/* Stats Grid */}
      <div className="grid grid-cols-2 gap-3 mb-4">
        <div className="bg-gray-700 rounded-lg p-3 text-center">
          <p className="text-gray-400 text-xs">Total Referrals</p>
          <p className="text-white text-2xl font-bold">{stats.totalReferrals}</p>
        </div>
        <div className="bg-gray-700 rounded-lg p-3 text-center">
          <p className="text-gray-400 text-xs">Total Earned</p>
          <p className="text-green-400 text-2xl font-bold">₹{stats.totalEarned}</p>
        </div>
        <div className="bg-gray-700 rounded-lg p-3 text-center">
          <p className="text-gray-400 text-xs">Coupons Used</p>
          <p className="text-white text-2xl font-bold">{stats.activeCoupons}</p>
        </div>
        <div className="bg-gray-700 rounded-lg p-3 text-center">
          <p className="text-gray-400 text-xs">Active Coupons</p>
          <p className="text-yellow-400 text-2xl font-bold">
            {stats.couponsGenerated - stats.totalReferrals}
          </p>
        </div>
      </div>
      
      {/* Recent Referrals */}
      {stats.recentReferrals.length > 0 && (
        <div className="mt-3">
          <h4 className="text-gray-400 text-sm mb-2">📋 Recent Referrals</h4>
          <div className="space-y-2">
            {stats.recentReferrals.map((ref, index) => (
              <div key={index} className="bg-gray-700/50 rounded-lg p-2 flex justify-between items-center">
                <div>
                  <p className="text-white text-sm font-medium">{ref.name}</p>
                  <p className="text-gray-500 text-xs">📱 {ref.mobile}</p>
                </div>
                <div className="text-right">
                  <p className="text-green-400 text-sm font-bold">+₹{ref.amount}</p>
                  <p className="text-gray-500 text-xs">{ref.date}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
      
      {/* Info Message */}
      <div className="mt-4 p-3 bg-blue-600/20 rounded-lg border border-blue-500/30">
        <p className="text-blue-400 text-xs text-center">
          💡 Share your coupon with friends. When they register, you get ₹20 and they get ₹10!
        </p>
      </div>
    </div>
  )
}